### ISSUE TITLE
Support and Implementation Details for Rails 7

### ISSUE THREAD

**Issue by epidevops** [blocknotes/activeadmin_dynamic_fields#24]
Does this gem work for a rails 7 importmaps implementation?  I have implemented according to the non-webpacker guide.

I have installed it and am getting the following error
```
active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3773 jQuery.Deferred exception: Cannot read properties of undefined (reading 'substr') TypeError: Cannot read properties of undefined (reading 'substr')
    at dfSetupField (http://localhost:3000/assets/activeadmin/dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:65:18)
    at HTMLInputElement.<anonymous> (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:54591:5)
    at Function.each (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:383:19)
    at jQuery.fn.init.each (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:205:17)
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:54590:142)
    at mightThrow (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3479:29)
    at process (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3547:12) undefined
jQuery.Deferred.exceptionHook @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3773
process @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3551
setTimeout (async)
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3592
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3351
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
ready @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3834
completed @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3844
active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3773 jQuery.Deferred exception: Cannot read properties of undefined (reading 'substr') TypeError: Cannot read properties of undefined (reading 'substr')
    at dfSetupField (http://localhost:3000/assets/activeadmin/dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:65:18)
    at HTMLInputElement.<anonymous> (http://localhost:3000/assets/activeadmin/dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:162:5)
    at Function.each (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:383:19)
    at jQuery.fn.init.each (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:205:17)
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/activeadmin/dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:161:142)
    at mightThrow (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3479:29)
    at process (http://localhost:3000/assets/active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3547:12) undefined
jQuery.Deferred.exceptionHook @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3773
process @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3551
setTimeout (async)
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3592
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3351
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
ready @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3834
completed @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3844
active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3783 Uncaught TypeError: Cannot read properties of undefined (reading 'substr')
    at dfSetupField (dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:65:18)
    at HTMLInputElement.<anonymous> (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:54591:5)
    at Function.each (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:383:19)
    at jQuery.fn.init.each (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:205:17)
    at HTMLDocument.<anonymous> (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:54590:142)
    at mightThrow (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3479:29)
    at process (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3547:12)
dfSetupField @ dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:65
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:54591
each @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:383
each @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:205
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:54590
mightThrow @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3479
process @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3547
setTimeout (async)
jQuery.readyException @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3782
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3802
mightThrow @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3479
process @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3547
setTimeout (async)
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3592
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3351
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
process @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3567
setTimeout (async)
(anonymous) @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3592
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3351
fire @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3213
fireWith @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3343
ready @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3834
completed @ active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3844
active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3783 Uncaught TypeError: Cannot read properties of undefined (reading 'substr')
    at dfSetupField (dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:65:18)
    at HTMLInputElement.<anonymous> (dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:162:5)
    at Function.each (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:383:19)
    at jQuery.fn.init.each (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:205:17)
    at HTMLDocument.<anonymous> (dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:161:142)
    at mightThrow (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3479:29)
    at process (active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3547:12)
```

**Comment by blocknotes** [comment]
> Does this gem work for a rails 7 importmaps implementation? I have implemented according to the non-webpacker guide.
> 
> I have installed it and am getting the following error
> 
> ```
> active_admin-d81fcd50ea26a294816d55dd8fa3a3840381fbaa776b65a6b242d3eec2610558.js:3773 jQuery.Deferred exception: Cannot read properties of undefined (reading 'substr') TypeError: Cannot read properties of undefined (reading 'substr')
>     at dfSetupField (http://localhost:3000/assets/activeadmin/dynamic_fields-b1e8a0a3194d41b3af16532e01aecf823d396b7bf4d1b7eb747c9fb002429230.js:65:18)
> ...
> ```

What's the version of *activeadmin_dynamic_fields*?

`dfSetupField` is an old method.

**Comment by blocknotes** [comment]
If you are using ActiveAdmin 3.x, it could be using an older version of *activeadmin_dynamic_fields* due an old misconfiguration. I have recently release a new version that allow the usage of ActiveAdmin 3.x

Can you try a `bundle update activeadmin_dynamic_fields`?

**Comment by blocknotes** [comment]
I'm closing this issue due to inactivity, feel free to reopen it if it isn't solved
